### ISSUE TITLE
Return responses as JSON

### ISSUE THREAD

**Issue by alanbacon** [foxthefox/yamaha-yxc-nodejs#3]
Hi i created a PR to parse the responses into JSON automatically: would you mind taking a look please:

https://github.com/foxthefox/yamaha-yxc-nodejs/pull/2 

thanks

**Comment by foxthefox** [comment]
It is probably a breaking change and someone has to adopt to it.

**Comment by foxthefox** [comment]
at least iobroker is recognizing it
